// import { Course } from "./CourseTable/CourseTable";

// const mockCourses: Course[] = [
//   {
//     id: 1,
//     title: "Leadership Training",
//     instructor: "Olivia Wilson",
//     category: "Management",
//     status: "Published",
//     enrollments: 543,
//   },
//   {
//     id: 2,
//     title: "Customer Service Excellence",
//     instructor: "James Taylor",
//     category: "Customer Service",
//     status: "Published",
//     enrollments: 967,
//   },
//   {
//     id: 3,
//     title: "Advanced Data Analytics",
//     instructor: "Isabella Martinez",
//     category: "Technology",
//     status: "Published",
//     enrollments: 1089,
//   },
//   {
//     id: 4,
//     title: "Time Management Fundamentals",
//     instructor: "Ethan Anderson",
//     category: "Productivity",
//     status: "Draft",
//     enrollments: 1245,
//   },
//   {
//     id: 5,
//     title: "Project Management Basics",
//     instructor: "Ava Thomas",
//     category: "Management",
//     status: "Published",
//     enrollments: 967,
//   },
//   {
//     id: 6,
//     title: "Communication Skills",
//     instructor: "Noah Garcia",
//     category: "Communication",
//     status: "Published",
//     enrollments: 789,
//   },
//   {
//     id: 7,
//     title: "Team Building Strategies",
//     instructor: "Sophia Brown",
//     category: "Management",
//     status: "Published",
//     enrollments: 852,
//   },
//   {
//     id: 8,
//     title: "Data Visualization",
//     instructor: "Liam Davis",
//     category: "Technology",
//     status: "Draft",
//     enrollments: 641,
//   },
//   {
//     id: 9,
//     title: "Customer Experience Design",
//     instructor: "Mia Allen",
//     category: "Customer Service",
//     status: "Published",
//     enrollments: 1123,
//   },
//   {
//     id: 10,
//     title: "Strategic Planning",
//     instructor: "Benjamin Lee",
//     category: "Management",
//     status: "Published",
//     enrollments: 934,
//   },
//   {
//     id: 11,
//     title: "Advanced Excel",
//     instructor: "Chloe Miller",
//     category: "Productivity",
//     status: "Draft",
//     enrollments: 765,
//   },
//   {
//     id: 12,
//     title: "Conflict Resolution",
//     instructor: "Lucas Hall",
//     category: "Communication",
//     status: "Published",
//     enrollments: 821,
//   },
//   {
//     id: 13,
//     title: "Digital Marketing",
//     instructor: "Zoe Walker",
//     category: "Technology",
//     status: "Published",
//     enrollments: 1012,
//   },
//   {
//     id: 14,
//     title: "Time Management Fundamentals",
//     instructor: "Ethan Anderson",
//     category: "Productivity",
//     status: "Published",
//     enrollments: 1245,
//   },
//   {
//     id: 15,
//     title: "Project Management Basics",
//     instructor: "Ava Thomas",
//     category: "Management",
//     status: "Draft",
//     enrollments: 967,
//   },
// ];

// export default mockCourses;
